version: 2
updates:
    -   package-ecosystem: "github-actions" # TODO: consider adding cooldown/groups to limit PR volume
        directory: "/"
        schedule:
            interval: "weekly"
    -   package-ecosystem: "maven" # TODO: consider adding cooldown/groups to limit PR volume
        directory: "/"
        schedule:
            interval: "weekly"
    -   package-ecosystem: "docker" # TODO: consider adding cooldown/groups to limit PR volume
        directory: "/"
        schedule:
            interval: "weekly"
