name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main

jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            -   name: Setup python
                uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
                with:
                    python-version: "3.9"
            -   name: Setup Java
                uses: ./.github/actions/java-setup
                with:
                    cache: ""
            -   name: Pre-commit checks
                uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
            -   name: pre-commit-c-lite
                uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
                if: always()
    build:
        runs-on: ${{ matrix.os }}
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            matrix:
                os: [ windows-latest, ubuntu-latest, macos-15-intel ]
            max-parallel: 1
        steps:
            -   uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            -   name: Set up JDK
                uses: ./.github/actions/java-setup
                with:
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
